esphome:
  project:
    name: "Tweakers.Quatt Modbus sniffer"
    version: "v1.1.0"

external_components:
  # use all components from GitHub repository
  - source:
      type: git
      url: https://github.com/M10tech/Quatt-sniffer
      #type: local
      #path: components
    components: [ modbus, modbus_controller ]
    #refresh: 5min  ## use this temporarily if you recently updated the repo, else disable for default 24h

# Enable logging
logger:
  #baud_rate: 0                         ## Turn off logging via UART (set baudrate to 0) in case the RS485 uses the onboard UART (tx/rx)
                                        ## However, in sniffer mode and with detached TX hardware trace this is not needed
  level: DEBUG
  logs:
    uart_debug: ERROR                   ## suppress log-messages from uart
    modbus: DEBUG                        ## suppress log-messages from modbus
    modbus_controller.sensor: DEBUG      ## suppress log-messages from modbus_controller.sensor
    sensor: DEBUG                        ## suppress log-messages from modbus_controller


# Configuration of UART with Quatt modbus connection-parameters
uart:
  id: uart_bus
  # tx_pin: GPIO21    ## just listening: tx_pin not specified  BUT must kill TX output hardware trace anyway!
  rx_pin: ${uart_rx_pin}
  baud_rate: 19200
  data_bits: 8
  parity: EVEN
  stop_bits: 1

modbus:
  uart_id: uart_bus
  id: mod_bus
  role: sniffer

modbus_controller:
- id: modbus_device_1
  address: 1               ## address of Quatt HP1 on the bus
  modbus_id: mod_bus

sensor: ## remember this setup MUST match the commands that a CIC sends to a Quatt
## these can be detected in verbose mode of modbus  and you can check the ranges that modbus_controller config reports
## first, there are 4 individual write commands
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Compressor Level set by CiC"
  register_type: holding
  address: 1999    ## address of the register inside the Quatt outdoor unit
  state_class: "measurement"
  filters:
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 10
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Pump Mode set by CiC"
  register_type: holding
  address: 2010

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Pump Level set by CiC"
  register_type: holding
  address: 2015
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 10
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Working Mode set by CiC"
  register_type: holding
  address: 3999

## next, use register_count: to make one read range from 2099 to 2138
## https://esphome.io/components/modbus_controller#optimizing-modbus-communications
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Working Mode Actual"
  register_type: holding
  address: 2099

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Compressor AC Voltage"
  register_type: holding
  address: 2100
  unit_of_measurement: "V"
  device_class: "voltage"
  state_class: "measurement"
  accuracy_decimals: 1
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 300
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Compressor AC Current"
  register_type: holding
  address: 2101
  unit_of_measurement: "A"
  device_class: "current"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - multiply: 0.1
    - clamp:
        min_value: 0
        max_value: 16
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Compressor Frequency Demand"
  register_type: holding
  address: 2102
  unit_of_measurement: "Hz"
  device_class: "frequency"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Compressor Frequency Actual"
  register_type: holding
  address: 2103
  unit_of_measurement: "Hz"
  device_class: "frequency"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true


- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Fan Speed Maximum"
  icon: mdi:fan
  register_type: holding
  address: 2104
  unit_of_measurement: "RPM"
  device_class: "speed"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 1000
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Fan Speed Actual"
  icon: mdi:fan
  register_type: holding
  address: 2105
  register_count: 2 ## fill gap for 2106
  unit_of_measurement: "RPM"
  device_class: "speed"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 1000
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Electric Expansion Valve"
  register_type: holding
  address: 2107
  unit_of_measurement: "p"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 1000
        ignore_out_of_range: true

## Some of the register 2108 status bits placed into binary sensors in the next section
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Other bits R2108"
  register_type: holding
  address: 2108
  bitmask: 0xf782   ## all the remaining bits
  filters:
    - multiply: 2   ## due to bitmask doing mask_and_shift_by_rightbit our mask divides by 2 which we undo

## we cannot remove this register since this will mess up the previous bitmask register, so internal=true
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - EV1 steps"
  internal: true
  register_type: holding
  address: 2109
  unit_of_measurement: "p"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 1000
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Outside Temperature"
  register_type: holding
  address: 2110
  unit_of_measurement: "째C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Evaporator Coil Temperature"
  register_type: holding
  address: 2111
  unit_of_measurement: "째C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Gas Discharge Temperature"
  register_type: holding
  address: 2112
  unit_of_measurement: "째C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 150
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Gas Return Temperature"
  register_type: holding
  address: 2113
  register_count: 3 ## fill gap for 2114-2115
  unit_of_measurement: "째C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Evaporator Pressure"
  register_type: holding
  address: 2116
  unit_of_measurement: "bar"
  device_class: "pressure"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - multiply: 0.1
    - clamp:
        min_value: 0
        max_value: 20
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Condenser Pressure"
  register_type: holding
  address: 2117
  unit_of_measurement: "bar"
  device_class: "pressure"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - multiply: 0.1
    - clamp:
        min_value: 0
        max_value: 60
        ignore_out_of_range: true

## Register 2118 (defrost) is placed into binary sensors in the next section

## Some of the register 2119 status bits placed into binary sensors in the next section
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Status bits R2119"
  register_type: holding
  address: 2119

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Status bits R2120"
  register_type: holding
  address: 2120

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Status bits R2121"
  register_type: holding
  address: 2121

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Firmware Version"
  register_type: holding
  address: 2122

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - EEPROM Version"
  register_type: holding
  address: 2123
  register_count: 8 ## fill gap for 2124-2130

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Condensing Temperature"
  register_type: holding
  address: 2131
  unit_of_measurement: "째C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Evaporating Temperature"
  register_type: holding
  address: 2132
  unit_of_measurement: "째C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Water In Temperature"
  register_type: holding
  address: 2133
  unit_of_measurement: "째C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Water Out Temperature"
  register_type: holding
  address: 2134
  unit_of_measurement: "째C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Condenser Coil Temperature"
  register_type: holding
  address: 2135
  register_count: 2 ## fill gap for 2136
  unit_of_measurement: "째C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Pump Power"
  register_type: holding
  address: 2137
  unit_of_measurement: "W"
  device_class: "power"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Pump Flow"
  register_type: holding
  address: 2138
  unit_of_measurement: "L/h"
  device_class: "volume_flow_rate"
  state_class: "measurement"
  icon: mdi:gauge
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - multiply: 0.618


binary_sensor:
## at least bits 0,2,4,5,6,11 are used for status in R2108
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Fan Low Speed Mode" #R2108b0
  register_type: holding
  address: 2108
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Bottom Heater" #R2108b2
  register_type: holding
  address: 2108
  bitmask: 0x4
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Crankcase Heater" #R2108b3
  register_type: holding
  address: 2108
  bitmask: 0x8
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Fan Defrost Speed Mode" #R2108b4
  register_type: holding
  address: 2108
  bitmask: 0x10
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Fan High Speed Mode" #R2108b5
  register_type: holding
  address: 2108
  bitmask: 0x20
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - 4way Valve" #R2108b6
  register_type: holding
  address: 2108
  bitmask: 0x40
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Pump Relay" #R2108b11
  register_type: holding
  address: 2108
  bitmask: 0x800

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Defrost Mode" #R2118b0
  icon: mdi:snowflake
  register_type: holding
  address: 2118

##Selection of register 2119 status bits put into binary sensors
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Alarm - Main Line Current" #R2119b0
  icon: mdi:message-alert
  register_type: holding
  address: 2119
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Info - Compressor Oil Return" #R2119b3
  icon: mdi:message-alert
  register_type: holding
  address: 2119
  bitmask: 0x8
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Alarm - High Pressure Switch" #R2119b4
  icon: mdi:message-alert
  register_type: holding
  address: 2119
  bitmask: 0x10
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Alarm - 1st Start Pre-heat" #R2119b6
  icon: mdi:message-alert
  register_type: holding
  address: 2119
  bitmask: 0x40
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Alarm - AC High/Low Voltage" #R2119b9
  icon: mdi:message-alert
  register_type: holding
  address: 2119
  bitmask: 0x200
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Alarm - Low Pressure Switch" #R2119b12
  icon: mdi:message-alert
  register_type: holding
  address: 2119
  bitmask: 0x1000
