modbus_controller:
- id: modbus_device_2
  address: 2               ## address of Quatt HP2 on the bus
  modbus_id: mod_bus

sensor: ## remember this setup MUST match the commands that a CIC sends to a Quatt
## these can be detected in verbose mode of modbus  and you can check the ranges that modbus_controller config reports
## first, there are 4 individual write commands
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - cmd_compressorlevel"
  register_type: holding
  address: 1999    ## address of the register inside the Quatt outdoor unit
  state_class: "measurement"
  filters:
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 10
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - cmd_pumpmode"
  register_type: holding
  address: 2010

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - cmd_pumplevel"
  register_type: holding
  address: 2015
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 10
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - cmd_workmode"
  register_type: holding
  address: 3999

## next, use register_count: to make one read range from 2099 to 2138
## https://esphome.io/components/modbus_controller#optimizing-modbus-communications
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Workmode"
  register_type: holding
  address: 2099

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - AC voltage"
  register_type: holding
  address: 2100
  unit_of_measurement: "V"
  device_class: "voltage"
  state_class: "measurement"
  accuracy_decimals: 1
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 300
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - AC current"
  register_type: holding
  address: 2101
  unit_of_measurement: "A"
  device_class: "current"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - multiply: 0.1
    - clamp:
        min_value: 0
        max_value: 16
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Compressor frequency demand"
  register_type: holding
  address: 2102
  unit_of_measurement: "Hz"
  device_class: "frequency"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Compressor frequency"
  register_type: holding
  address: 2103
  unit_of_measurement: "Hz"
  device_class: "frequency"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true


- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Fan speed max"
  icon: mdi:fan
  register_type: holding
  address: 2104
  unit_of_measurement: "RPM"
  device_class: "speed"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 1000
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Fan speed"
  icon: mdi:fan
  register_type: holding
  address: 2105
  register_count: 2 ## fill gap for 2106
  unit_of_measurement: "RPM"
  device_class: "speed"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 1000
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - EEV steps"
  register_type: holding
  address: 2107
  unit_of_measurement: "p"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 1000
        ignore_out_of_range: true

## Some of the register 2108 status bits placed into binary sensors in the next section
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - R2108_other_bits"
  register_type: holding
  address: 2108
  bitmask: 0xf782   ## all the remaining bits
  filters:
    - multiply: 2   ## due to bitmask doing mask_and_shift_by_rightbit our mask divides by 2 which we undo

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - EV1 steps"
  register_type: holding
  address: 2109
  unit_of_measurement: "p"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - throttle: ${throttling_value}
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 1000
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Outside temperature"
  register_type: holding
  address: 2110
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Evaporator coil temperature"
  register_type: holding
  address: 2111
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Gas discharge temperature"
  register_type: holding
  address: 2112
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 150
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Gas return temperature"
  register_type: holding
  address: 2113
  register_count: 3 ## fill gap for 2114-2115
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Evaporator pressure"
  register_type: holding
  address: 2116
  unit_of_measurement: "bar"
  device_class: "pressure"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - multiply: 0.1
    - clamp:
        min_value: 0
        max_value: 20
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Condenser pressure"
  register_type: holding
  address: 2117
  unit_of_measurement: "bar"
  device_class: "pressure"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - multiply: 0.1
    - clamp:
        min_value: 0
        max_value: 60
        ignore_out_of_range: true

## Register 2118 (defrost) is placed into binary sensors in the next section

## Some of the register 2119 status bits placed into binary sensors in the next section
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Status bits 1"
  register_type: holding
  address: 2119

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Status bits 2"
  register_type: holding
  address: 2120

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Status bits 3"
  register_type: holding
  address: 2121
  register_count: 10 ## fill gap for 2122-2130

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Condensing temperature"
  register_type: holding
  address: 2131
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Evaporating temperature"
  register_type: holding
  address: 2132
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Water in temperature"
  register_type: holding
  address: 2133
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Water out temperature"
  register_type: holding
  address: 2134
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Inner coil temperature"
  register_type: holding
  address: 2135
  register_count: 2 ## fill gap for 2136
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Pump Power"
  register_type: holding
  address: 2137
  unit_of_measurement: "W"
  device_class: "power"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Flow"
  register_type: holding
  address: 2138
  unit_of_measurement: "L/h"
  device_class: "volume_flow_rate"
  state_class: "measurement"
  icon: mdi:gauge
  accuracy_decimals: 2
  filters:
    - throttle: ${throttling_value}
    - multiply: 0.618


binary_sensor:
## at least bits 0,2,4,5,6,11 are used for status in R2108
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - R2108b0_comp_low_fan"
  register_type: holding
  address: 2108
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - R2108b2_bottom_heater"
  register_type: holding
  address: 2108
  bitmask: 0x4
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - R2108b3_???"
  register_type: holding
  address: 2108
  bitmask: 0x8
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - R2108b4_crankcase_heater?"
  register_type: holding
  address: 2108
  bitmask: 0x10
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - R2108b5_comp_high_fan"
  register_type: holding
  address: 2108
  bitmask: 0x20
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - R2108b6_4way_valve"
  register_type: holding
  address: 2108
  bitmask: 0x40
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - R2108b11 DC_Pump_Relay"
  register_type: holding
  address: 2108
  bitmask: 0x800

- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - R2118_Defrost"
  icon: mdi:snowflake
  register_type: holding
  address: 2118

##Selection of register 2119 status bits put into binary sensors
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Protection - Main line current"
  icon: mdi:message-alert
  register_type: holding
  address: 2119
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Protection - Compressor oil return"
  icon: mdi:message-alert
  register_type: holding
  address: 2119
  bitmask: 0x8
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Protection - High Pressure switch"
  icon: mdi:message-alert
  register_type: holding
  address: 2119
  bitmask: 0x10
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Protection - 1st start pre-heat"
  icon: mdi:message-alert
  register_type: holding
  address: 2119
  bitmask: 0x40
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Protection - AC high/low voltage"
  icon: mdi:message-alert
  register_type: holding
  address: 2119
  bitmask: 0x200
- platform: modbus_controller
  modbus_controller_id: modbus_device_2
  name: "HP2 - Protection - Low pressure switch"
  icon: mdi:message-alert
  register_type: holding
  address: 2119
  bitmask: 0x1000
