esphome:
  name: quatt-sniffer
  friendly_name: QMBus

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: !secret QMB_api

ota:
  - platform: esphome
    password: !secret QMB_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
  #  ssid: "QMBus_AP"
  #  password: !secret QMB_AP

#captive_portal:
    
external_components:
  # use all components from a local folder
  - source:
      type: local
      path: components
    components: [ modbus, modbus_controller]

# Enable logging
logger:
  #baud_rate: 0                         ## Igor Ybema: make sure to turn of logging via UART (set baudrate to 0) as the RS485 uses the onboard UART (tx/rx)
  #however, in sniffer mode and with detached TX hardware trace this is not needed
  level: DEBUG
  logs:
    uart_debug: ERROR                  ## onderdruk log-berichten van uart
    modbus: ERROR                      ## onderdruk log-berichten van modbus
    modbus_controller.sensor: ERROR    ## onderdruk log-berichten van modbus_controller.sensor
    modbus_controller: ERROR           ## onderdruk log-berichten van modbus_controller

# Configuratie van UART op Quatt modbus connectie-parameters
uart:                 ## Igor Ybema: The RS485 is connected to the ESP32-C3 via hardware uart, rx/tx (gpio20/gpio21).
  id: uart_bus
  # tx_pin: GPIO21    ## just listening: tx_pin not specified  BUT must kill TX output hardware trace anyway!
  rx_pin: GPIO23      ## on ESP32C3 use GPIO20, on ESP32 use GPIO23
  baud_rate: 19200    ## start bit na 52us: 19200 baud zie https://discord.com/chann...24364/1232080954466631761
  data_bits: 8
  parity: EVEN
  stop_bits: 1

# Configuratie modbus in ESPHome
modbus:
  uart_id: uart_bus
  id: mod_bus
  role: sniffer

# Configuratie modbus_controller voor wegschrijven Quatt modbus-data uit uart naar HA-sensoren
modbus_controller:
- id: modbus_device_1
  address: 1               ## address of the Modbus slave device on the bus
  modbus_id: mod_bus

sensor: ## remember this setup MUST match the commands that a CIC sends to a Quatt
# HP1
## first, there are 4 individual write commands
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - cmd_compressorlevel"
  register_type: holding
  address: 1999
  state_class: "measurement"
  filters:
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 10
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - cmd_pumpmode"
  register_type: holding
  address: 2010

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - cmd_pumplevel"
  register_type: holding
  address: 2015
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 10
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - cmd_workmode"
  register_type: holding
  address: 3999

## next, use register_count: to make one read range from 2099 to 2138
## https://esphome.io/components/modbus_controller#optimizing-modbus-communications
- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Workmode"
  register_type: holding
  address: 2099    ## address of the register inside the Modbus slave device

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - AC voltage"
  register_type: holding
  address: 2100    ## address of the register inside the Modbus slave device
  unit_of_measurement: "V"
  device_class: "voltage"
  state_class: "measurement"
  accuracy_decimals: 1
  filters:
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 300
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - AC current"
  register_type: holding
  address: 2101    ## address of the register inside the Modbus slave device
  unit_of_measurement: "A"
  device_class: "current"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - multiply: 0.1
    - clamp:
        min_value: 0
        max_value: 10
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Compressor frequency demand"
  register_type: holding
  address: 2102    ## address of the register inside the Modbus slave device
  unit_of_measurement: "Hz"
  device_class: "frequency"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Compressor frequency"
  register_type: holding
  address: 2103    ## address of the register inside the Modbus slave device
  # register_count: 7 ## fill gap for 2104-2109
  unit_of_measurement: "Hz"
  device_class: "frequency"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true


- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Fan speed max"
  register_type: holding
  address: 2104    ## address of the register inside the Modbus slave device
  # register_count: 7 ## fill gap for 2104-2109
  unit_of_measurement: "RPM"
  device_class: "speed"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 1000
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Fan speed"
  register_type: holding
  address: 2105    ## address of the register inside the Modbus slave device
  register_count: 2 ## fill gap for 2106
  unit_of_measurement: "RPM"
  device_class: "speed"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 1000
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - EEV steps"
  register_type: holding
  address: 2107    ## address of the register inside the Modbus slave device
  unit_of_measurement: "p"
  # device_class: "speed"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 1000
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - General Status"
  register_type: holding
  address: 2108

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - EV1 steps"
  register_type: holding
  address: 2109    ## address of the register inside the Modbus slave device
  unit_of_measurement: "p"
  # device_class: "speed"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 1000
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Outside temperature"
  register_type: holding
  address: 2110    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Evaporator coil temperature"
  register_type: holding
  address: 2111    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true    

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Gas discharge temperature"
  register_type: holding
  address: 2112    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 150
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Gas return temperature"
  register_type: holding
  address: 2113    ## address of the register inside the Modbus slave device
  register_count: 3 ## fill gap for 2114-2115
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Evaporator pressure"
  register_type: holding
  address: 2116    ## address of the register inside the Modbus slave device
  unit_of_measurement: "bar"
  device_class: "pressure"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - multiply: 0.1
    - clamp:
        min_value: 0
        max_value: 10
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Condenser pressure"
  register_type: holding
  address: 2117    ## address of the register inside the Modbus slave device
  unit_of_measurement: "bar"
  device_class: "pressure"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - multiply: 0.1
    - clamp:
        min_value: 0
        max_value: 60
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Defrost Flag"
  register_type: holding
  address: 2118

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Status bits 1"
  register_type: holding
  address: 2119

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Status bits 2"
  register_type: holding
  address: 2120

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Status bits 3"
  register_type: holding
  address: 2121
  register_count: 10 ## fill gap for 2122-2130

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Condensing temperature"
  register_type: holding
  address: 2131    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Evaporating temperature"
  register_type: holding
  address: 2132    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: -30
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Water in temperature"
  register_type: holding
  address: 2133    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Water out temperature"
  register_type: holding
  address: 2134    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Inner coil temperature"
  register_type: holding
  address: 2135    ## address of the register inside the Modbus slave device
  register_count: 2 ## fill gap for 2136
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true    

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Pump"        ##Quatt: "circulating pump duty cycle"
  register_type: holding
  address: 2137    ## address of the register inside the Modbus slave device
  unit_of_measurement: "W"  ##Quatt: "%"
  device_class: "power"
  state_class: "measurement"
  accuracy_decimals: 2
  filters:
    - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "HP1 - Flow"
  register_type: holding
  address: 2138    ## address of the register inside the Modbus slave device
  unit_of_measurement: "L/h"
  device_class: "volume_flow_rate"
  state_class: "measurement"
  icon: mdi:gauge
  accuracy_decimals: 2
  filters:
    - multiply: 0.618
